server:
  port: 9092

spring:
  application:
    name: pay-boos-web
  profiles:
    active: @profile.active@
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: top.inson.springboot.data.entity
  mapper-locations: classpath:mappers/**/*.xml

logging:
  config: classpath:logback-black.xml
