server:
  port: 9092

spring:
  application:
    name: pay-boos-web
  profiles:
    active: @profile.active@
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    pool:
      #连接池最大连接数（使用负数表示没有限制）
      max-active: 8
      #连接池最大阻塞等待时间（使用复制表示没有限制）
      max-wait: -1
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中最小空闲连接
      min-idle: 0
    database: 0
    timeout: 1000

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: top.inson.springboot.data.entity
  mapper-locations: classpath:mappers/**/*.xml

logging:
  config: classpath:logback-black.xml

#忽略地址
ignore:
  urls:
    - /swagger-resources/**
    - /swagger-ui.html
    - /webjars/**
    - /*/api-docs
    - /avatar/**
    - /file/**
    - /druid/**

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  # 在线用户key
  online: online-token
  # 验证码
  onlineKey: code-key

swagger:
  title: ${spring.application.name}
  description: 管理端后台接口
  version: 1.0.0
  contact:
    name: jingjitree
    email: jingjitree@gmail.com
  global-operation-parameters:
    - name: Authorization
      description: 登陆令牌
      modelRef: string
      parameterType: header
      required: true
  exclude-path:
    - /error

