spring:
  datasource:
    druid:
      url: jdbc:mysql://10.13.132.26:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
      username: java
      password: Tts1608

  redis:
    host: 127.0.0.1
    port: 6379
    password: UxMiJ9