spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.254:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
      username: root
      password: shihuai1993A

  redis:
    host: 192.168.1.254
    port: 6379

pay:
  baseUrl: http://api3.taotaoshi.cn/notify
