server:
  port: 9191
  servlet:
    context-path: /notify

spring:
  application:
    name: pay-notify-web
  profiles:
    active: @profile.active@
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    pool:
      #连接池最大连接数（使用负数表示没有限制）
      max-active: 8
      #连接池最大阻塞等待时间（使用复制表示没有限制）
      max-wait: -1
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中最小空闲连接
      min-idle: 0
    database: 1
    timeout: 1000

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: top.inson.springboot.data.entity
  mapper-locations: classpath:mappers/**/*.xml

logging:
  config: classpath:logback-black.xml